"""
Configuration settings for MHL scraper.
"""
import os
import toml
from pathlib import Path
from typing import Dict, Any, Optional


class ScraperConfig:
    """Configuration for the MHL scraper."""

    # League ID for API requests
    LEAGUE_ID = "31917"

    # Default MHL API URL
    DEFAULT_API_URL = "https://api.spof.io/mhl/v1"

    # Default API timeout in seconds
    DEFAULT_API_TIMEOUT = 30


class UserConfig:
    """User-specific configuration stored in a TOML config file."""

    DEFAULT_CONFIG_PATH = "config.toml"

    def __init__(self, config_path: Optional[str] = None):
        """
        Initialize user configuration.

        Args:
            config_path: Path to config file. If None, uses default path.
        """
        self.config_path = config_path or self.DEFAULT_CONFIG_PATH
        self.config = self._load_config()
        self._division_name_map = {}  # For storing division ID -> name mapping
        self._team_name_for_id = None  # For storing team name for team_id

    def _load_config(self) -> Dict[str, Any]:
        """Load configuration from TOML file."""
        path = Path(self.config_path)
        if path.exists():
            try:
                with open(path, 'r', encoding='utf-8') as f:
                    return toml.load(f)
            except Exception as e:
                print(f"Warning: Could not load config from {self.config_path}: {e}")
                return self._get_default_config()
        return self._get_default_config()

    def _get_default_config(self) -> Dict[str, Any]:
        """Get default configuration."""
        return {
            "season_id": None,
            "season_name": None,
            "division_ids": [],
            "team_id": None,
            "team_name": None,
            "teamlinkt_api_key": None,
            "teamlinkt_access_code": None,
            "teamlinkt_user_id": None,
            "api": {
                "url": None,
                "timeout": None,
            },
        }

    def save(self) -> bool:
        """
        Save configuration to TOML file with comments for division names.

        Returns:
            True if successful, False otherwise
        """
        try:
            path = Path(self.config_path)
            path.parent.mkdir(parents=True, exist_ok=True)

            # Ensure file is created with 600 permissions if it doesn't exist
            if not path.exists():
                path.touch(mode=0o600)
            else:
                # If it exists, enforce 600 permissions
                path.chmod(0o600)

            with open(path, 'w', encoding='utf-8') as f:
                # Write header comment
                f.write("# MHL Scout Configuration\n")
                f.write("# Generated by 'mhl-scout config' command\n\n")

                # Write season configuration with comments
                f.write("# Season Configuration\n")
                season_config = {
                    "season_id": self.config["season_id"],
                    "season_name": self.config["season_name"]
                }
                f.write(toml.dumps(season_config))
                f.write("\n")

                # Write division configuration with inline comments
                f.write("# Division Configuration\n")
                f.write("# Selected divisions to scrape\n")
                f.write("division_ids = [\n")

                division_ids = self.config.get("division_ids", [])
                for div_id in division_ids:
                    # Add comment with division name if we have it
                    comment = ""
                    if div_id in self._division_name_map:
                        comment = f"  # {self._division_name_map[div_id]}"
                    f.write(f'  "{div_id}",{comment}\n')

                f.write("]\n\n")

                # Write team configuration
                f.write("# Team Configuration\n")
                team_id = self.config.get("team_id")
                team_name = self.config.get("team_name")

                if team_id:
                    # Add comment with team name if we have it
                    comment = f"  # {self._team_name_for_id}" if self._team_name_for_id else ""
                    f.write(f'team_id = "{team_id}"{comment}\n')
                else:
                    f.write("# team_id = \"123456\"  # Your Team Name\n")

                if team_name:
                    team_config = {"team_name": team_name}
                    f.write(toml.dumps(team_config))
                else:
                    f.write("# team_name = \"Your Team Name\"\n")

                # Write TeamLinkt API credentials section
                f.write("\n# TeamLinkt API Credentials (Optional)\n")
                f.write("# Required for gamesheet/scoresheet access via the TeamLinkt mobile app API\n")
                f.write("# Extract these from Charles Proxy capture of the TeamLinkt iOS/Android app\n")
                f.write("# See GAMESHEET_API.md for instructions\n")
                f.write("#\n")
                f.write("# SECURITY WARNING: These are YOUR personal credentials. Do NOT share them.\n")
                f.write("# Consider using environment variables instead:\n")
                f.write("#   export TEAMLINKT_API_KEY=\"your_key\"\n")
                f.write("#   export TEAMLINKT_ACCESS_CODE=\"your_code\"\n")
                f.write("#\n")

                api_key = self.config.get("teamlinkt_api_key")
                access_code = self.config.get("teamlinkt_access_code")
                user_id = self.config.get("teamlinkt_user_id")

                if api_key:
                    f.write(f'teamlinkt_api_key = "{api_key}"      # hex string from Authorization header\n')
                else:
                    f.write('# teamlinkt_api_key = ""      # hex string from Authorization header\n')

                if access_code:
                    f.write(f'teamlinkt_access_code = "{access_code}"  # 40-character hex string (session token)\n')
                else:
                    f.write('# teamlinkt_access_code = ""  # 40-character hex string (session token)\n')

                if user_id:
                    f.write(f'teamlinkt_user_id = "{user_id}"      # Your user ID (optional, likely redundant)\n')
                else:
                    f.write('# teamlinkt_user_id = ""      # Your user ID (optional, likely redundant)\n')

                # Write MHL API configuration section
                f.write("\n# MHL Cloud API Configuration\n")
                f.write("# The CLI uses the cloud API by default for faster cached responses\n")
                f.write("# Use --direct flag to bypass the API and call TeamLinkt directly\n")
                f.write("#\n")
                f.write("# Environment variable MHL_API_URL overrides this setting\n")
                f.write("[api]\n")

                api_config = self.config.get("api", {})
                api_url = api_config.get("url") if isinstance(api_config, dict) else None
                api_timeout = api_config.get("timeout") if isinstance(api_config, dict) else None

                if api_url:
                    f.write(f'url = "{api_url}"\n')
                else:
                    f.write(f'# url = "{ScraperConfig.DEFAULT_API_URL}"  # Default API URL\n')

                if api_timeout:
                    f.write(f'timeout = {api_timeout}\n')
                else:
                    f.write(f'# timeout = {ScraperConfig.DEFAULT_API_TIMEOUT}  # Request timeout in seconds\n')

            print(f"Configuration saved to {self.config_path}")
            return True
        except Exception as e:
            print(f"Error saving config to {self.config_path}: {e}")
            return False

    def set_season(self, season_id: str, season_name: str) -> None:
        """Set the season configuration."""
        self.config["season_id"] = season_id
        self.config["season_name"] = season_name

    def set_divisions(self, division_ids: list, division_names: list) -> None:
        """Set the divisions configuration with name mapping for comments."""
        self.config["division_ids"] = division_ids
        # Store mapping for comments when saving
        self._division_name_map = dict(zip(division_ids, division_names))

    def set_team(self, team_id: str, team_name: str) -> None:
        """Set the team configuration with ID and name."""
        self.config["team_id"] = team_id
        self.config["team_name"] = team_name
        # Store team name for comment when saving
        self._team_name_for_id = team_name

    def set_team_name(self, team_name: str) -> None:
        """Set the team name configuration."""
        self.config["team_name"] = team_name

    def get_season_id(self) -> Optional[str]:
        """Get the configured season ID."""
        return self.config.get("season_id")

    def get_season_name(self) -> Optional[str]:
        """Get the configured season name."""
        return self.config.get("season_name")

    def get_division_ids(self) -> list:
        """Get the configured division IDs."""
        return self.config.get("division_ids", [])

    def get_division_names(self) -> list:
        """Get the configured division names from the name map."""
        division_ids = self.get_division_ids()
        return [self._division_name_map.get(div_id, div_id) for div_id in division_ids]

    def get_team_id(self) -> Optional[str]:
        """Get the configured team ID."""
        return self.config.get("team_id")

    def get_team_name(self) -> Optional[str]:
        """Get the configured team name."""
        return self.config.get("team_name")

    def get_teamlinkt_api_key(self) -> Optional[str]:
        """
        Get the TeamLinkt API key from env vars or config.

        Returns:
            API key if found, None otherwise.
        """
        # Check environment variable first (highest precedence)
        env_key = os.environ.get("TEAMLINKT_API_KEY")
        if env_key:
            return env_key

        return self.config.get("teamlinkt_api_key")

    def get_teamlinkt_access_code(self) -> Optional[str]:
        """
        Get the TeamLinkt access code from env vars or config.

        Returns:
            Access code if found, None otherwise.
        """
        # Check environment variable first (highest precedence)
        env_code = os.environ.get("TEAMLINKT_ACCESS_CODE")
        if env_code:
            return env_code

        return self.config.get("teamlinkt_access_code")

    def get_teamlinkt_user_id(self) -> Optional[str]:
        """
        Get the TeamLinkt user ID from env vars or config.

        Returns:
            User ID if found, None otherwise.
        """
        # Check environment variable first (highest precedence)
        env_user_id = os.environ.get("TEAMLINKT_USER_ID")
        if env_user_id:
            return env_user_id

        return self.config.get("teamlinkt_user_id")

    def get_api_url(self) -> str:
        """
        Get the MHL API URL with precedence: env var > config file > default.

        Returns:
            The API URL to use.
        """
        # Check environment variable first (highest precedence)
        env_url = os.environ.get("MHL_API_URL")
        if env_url:
            return env_url

        # Check config file
        api_config = self.config.get("api", {})
        if isinstance(api_config, dict):
            config_url = api_config.get("url")
            if config_url:
                return config_url

        # Fall back to default
        return ScraperConfig.DEFAULT_API_URL

    def get_api_timeout(self) -> int:
        """
        Get the API timeout in seconds.

        Returns:
            The timeout value in seconds (default: 30).
        """
        api_config = self.config.get("api", {})
        if isinstance(api_config, dict):
            timeout = api_config.get("timeout")
            if timeout is not None:
                return int(timeout)

        return ScraperConfig.DEFAULT_API_TIMEOUT

    def set_api_url(self, url: str) -> None:
        """Set the API URL in configuration."""
        if "api" not in self.config or not isinstance(self.config.get("api"), dict):
            self.config["api"] = {}
        self.config["api"]["url"] = url

    def set_api_timeout(self, timeout: int) -> None:
        """Set the API timeout in configuration."""
        if "api" not in self.config or not isinstance(self.config.get("api"), dict):
            self.config["api"] = {}
        self.config["api"]["timeout"] = timeout

    def is_configured(self) -> bool:
        """Check if configuration is set up."""
        return bool(self.config.get("season_id"))

    def __repr__(self) -> str:
        """String representation of config."""
        div_count = len(self.get_division_ids())
        return f"UserConfig(season={self.get_season_name()}, divisions={div_count}, team={self.get_team_name()})"
